### ISSUE TITLE
Problem About DPI

### ISSUE THREAD

**Issue by binzet-cmd** [Fortigate/AutoAFK#25]
I have a problem with DPI. I have set the DPI setting to 240 DPI. But AutoAFK still shows me that I should set the DPI setting to 240.

```
[08:01:49] Attempting to connect, make sure that BlueStacks is running!
[08:01:53] Port 5555 found in settings.ini, using that
[08:01:53] Device: 127.0.0.1:5555 successfully connected!
[08:01:53] Unsupported DPI! (240
Override). Please change your Bluestacks DPI to 240
```

![2uQJEh6HjT](https://github.com/Fortigate/AutoAFK/assets/141702863/839f6309-2880-4e70-99d7-16ce7c3f1b9f)

**Comment by Fortigate** [comment]
Thanks for the pics they make troubleshooting much easier

To check the resolution the bot runs `adb shell wm density` which should return one line `Physical density: ###`, we take the 3rd entry there and check if its 240, for some reason it's returning two lines on your emualator;

```
Physical density: 240
Override density: 200
```

So the 3rd entry includes the newline and Override and it fails the check. Should be simple enough to fix but I'm without internet for a while, can you try changing the device mdoel in Bluestacks settings and see if that fixes it? Else I'll make a new commit soon to address it.

**Comment by binzet-cmd** [comment]
Hi again,

First of all, I would like to thank you for your help. 

- [x] - When I checked the "density" in Blustacks settings and with ADB commands, it was seen as 240 DPI. 

![WindowsTerminal_fE1XL5Zwpn](https://github.com/Fortigate/AutoAFK/assets/141702863/d3916a24-0332-4023-bdc1-56089bb74b33)


- [x] - Then when I typed the DPI setting with _**".\adb.exe shell wm density 240"**_ the problem was fixed.

![WindowsTerminal_b5ecxB696Z](https://github.com/Fortigate/AutoAFK/assets/141702863/a9650bf0-87fe-407b-9322-9c6da3cf40b2)

```
[15:18:19] Attempting to connect, make sure that BlueStacks is running!
[15:18:23] Port 56990 found in settings.ini, using that
[15:18:23] Device: 127.0.0.1:56990 successfully connected!
[15:18:23] Searching for Campaign screen..
[15:18:27] Game Loaded!
```

The bot is working good now.

**Short solution:** ` .\adb.exe shell wm density 240`
