### ISSUE TITLE
Run Dailies purchased baits even when unticked

### ISSUE THREAD

**Issue by DnInYm** [Fortigate/AutoAFK#29]
In the latest release as of this ticket's creation, with baits disabled in the Shop Options menu, the application still automaticlaly purchased baits.

**Comment by DnInYm** [comment]
I think there's some sort of update that's not being passed. On changing options in the Select Activities menu, even though I disabled all but the merchant rewards collection, the application still tried to do all of the options I still had enabled. 

There isn't a "save" button for that menu, nor is there one for the shop. Without having looked at the code, my guess is that the information being changed isn't being pushed to the script's components on change. Seems like a caching problem.

**Comment by Fortigate** [comment]
Currently the settings file is updated when the checkboxes are selected or unselected which is a bit unclear, I'll add a button there.

Did you overwrite the existing settings.ini with the one from the new version? I have a feeling what happened is that `baits = True` exists in that, and then the new settings weren't loaded properly before running dailies after changing them in the UI. I'll look into it as I've added a ton of failsafes to read settings before most actions but it can be done in a cleaner way for sure.

**Comment by DnInYm** [comment]
I didn't check that file, have been operating purely through the UI

**Comment by Fortigate** [comment]
Made a save button to make sure we are storing changed values after changing them in settings, also a re-load of the settings file before we start running the shop purchases to ensure they are up to date, should fix this one
