### ISSUE TITLE
Fails during arena battles

### ISSUE THREAD

**Issue by skkAYE** [Fortigate/AutoAFK#31]
Hello, 

Thank you for your work, love it

There is a redundant error while doing my automatic dailies, it happens during the arena battles part.

It seems to me that the sleep time between choosing an enemy and clicking the "Battle" button is slightly too low.
Indeed, that part of the game is quite laggy, and it looks like the script is sometimes clicking "Battle" while the heroes are still charging, therefore it doesn't work.

It's able to keep going for other battles even if it fails, however, if it happens during the last battle the dailies may not be able to keep going.

PS : let me know if i shouldnt be posting this as an issue here! 

TY!

**Comment by Fortigate** [comment]
Hey, thanks!

I've noticed the same issue, I actually changed the code to check for the two arrow expand button on the left a while back as we were getting ghost clicks on the Battle button that was throwing everything out of whack when the bot couldn't detect the buttons after that. I'll change that to a `while` loop to make sure that we have definitely left the hero selection screen and hopefully that fixes it for good.
